const Data = [
  {
    id: 1,
    category: "education",
    icon: "icon-graduation",
    year: "06/2022 - actuel",
    title: "Développement et intégration du Web",
    desc: "Epitech - Marseille",
  },
  {
    id: 2,
    category: "education",
    icon: "icon-graduation",
    year: "10/2015 - 03/2019",
    title: "PhD. Physique de la matière condensée",
    desc: "Aix Marseille Université, Marseille",
  },
  {
    id: 3,
    category: "education",
    icon: "icon-graduation",
    year: "06/2013 - 07/2015",
    title: "MSc Sustainable Nuclear Energy, Application & Management",
    desc: "Ecole de Mines de Nantes, Nantes",
  },

    {
      id: 5,
      category: "experience",
      icon: "icon-briefcase",
      year: "10/2021 - 05/2022",
      title: "Jr. Développeur web",
      place: "Digitalphy, Benagaluru , India.",
      desc: "Développez des sites Web, explorez les technologies pour les entreprises et comprenez l'entreprise.",
    },
    {
      id: 6,
      category: "experience",
      icon: "icon-briefcase",
      year: "01/2020 - 03/2021",
      title: "Ingénieur de Recherche - Développeur",
      place: "CEA Cadarache, France.",
      desc: "Développer des modèles statistiques, intégrer des codes à l'aide d'outils, analyse de données avec python, modélisation de données avec OpenCalphad.",
    },
    {
      id: 7,
      category: "experience",
      icon: "icon-briefcase",
      year: "2009 - 2013",
      title: "Ingénieur de Recherche - Chargée des Affaires Projets",
      place: "CEA Cadarache, France.",
      desc: "Développer de nouveaux protocoles expérimentaux, mesurer et affiner les données issues des expériences et de la littérature, analyser et modéliser les données avec python, excel et Calphad.",
    },
    {
      id: 8,
      category: "experience",
      icon: "icon-briefcase",
      year: "2009 - 2013",
      title: "M2 Stage-Développeur",
      place: "Areva-CEA Marcoule, France.",
      desc: "Développement et benchmarking du code FEM, modélisation des données pour simuler les effets du stress à l'aide de la dynamique moléculaire.",
    },
  ];

export default Data